# Generated by Django 2.2.2 on 2021-12-29 11:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=256)),
                ('num_slots', models.PositiveIntegerField()),
                ('num_colors', models.PositiveIntegerField()),
                ('max_guesses', models.PositiveIntegerField()),
                ('secret_code', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(max_length=256)),
                ('colors', django.contrib.postgres.fields.jsonb.JSONField()),
                ('registration_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('black_pegs', models.PositiveIntegerField()),
                ('white_pegs', models.PositiveIntegerField()),
                ('a', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.GameModel')),
            ],
        ),
    ]
